version: '3.8'

services:
  # Database PostgreSQL untuk e-Gov
  db_egov:
    image: postgres:latest
    container_name: postgres-egov
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: egovkominfo
    volumes:
      - postgres_egov_data:/var/lib/postgresql

  # Storage MinIO untuk Aset Diskominfo
  storage_egov:
    image: minio/minio
    container_name: minio-egov
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_egov_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_egov_data:
  minio_egov_data: